"""
Django settings for maneu project.

Generated by 'django-maneu startproject' using Django 3.0.

For more information on this file, see
https:#docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https:#docs.djangoproject.com/en/3.0/ref/settings/
"""
import os

"""
Build paths inside the project like this: os.path.join(BASE_DIR, ...)
"""
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

"""
secret config
Quick-start development settings - unsuitable for production
See https:#docs.djangoproject.com/en/3.0/howto/deployment/checklist/
SECURITY WARNING: don't run with debug turned on in production!
SECURITY WARNING: keep the secret key used in production secret!
"""
DEBUG = True
SECRET_KEY = 'd&@vq_f^z79&w=nqqcm2vu#+gj8)_qdvy1t&agfxhmi74fwpr!'
ALLOWED_HOSTS = ['*']

"""
注册应用程序
"""
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'maneu',
    'maneu_admin',
    'maneu_guest',
    'maneu_index',
    'maneu_order',
    'maneu_report',
    'maneu_store',
]

"""
注册中间件
"""
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.UserMiddleware.UserMiddleware',  # 用户登录校验中间件
]

"""
根路由
"""
ROOT_URLCONF = 'maneu.urls'

"""
注册模板
"""
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + "/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

"""
WSGI_应用程序
"""
WSGI_APPLICATION = 'maneu.wsgi.application'

"""
配置数据库
https:#docs.djangoproject.com/en/3.0/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'maneu',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': '214772680',
    }
}

"""
密码验证
Password validation
https:#docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
"""
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""
国际化配置
Internationalization
https:#docs.djangoproject.com/en/3.0/topics/i18n/
"""
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = False

"""
Static files config
https:#docs.djangoproject.com/en/3.0/howto/static-files/
"""
STATIC_URL = '/static/'
STATIC_ROOT = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# settings.py 末尾追加
JWT_CONFIG = {
    'SECRET_KEY': SECRET_KEY,  # 直接用 Django 的 SECRET_KEY
    'ALGORITHM': 'HS256',
    'ACCESS_TOKEN_LIFETIME': 3600,  # 1 小时
    'REFRESH_TOKEN_LIFETIME': 604800,  # 7 天
}
#
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/0",  # 或 redis://:password@127.0.0.1:6379/0
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             # "PASSWORD": "your_redis_password",           # Redis密码
#             "SOCKET_TIMEOUT": 5,                         # 读写超时
#             "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",  # 数据压缩
#             "CONNECTION_POOL_KWARGS": {
#                 "max_connections": 100,                  # 连接池大小
#                 "health_check_interval": 30              # 连接健康检查
#             }
#         },
#         "KEY_PREFIX": "maneu"                            # Key前缀，防冲突
#     }
# }
