# Generated by Django 3.0 on 2022-10-10 00:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('maneu_order',
         '0002_maneubatch_maneuguess_maneuorder_maneuorderv2_maneustore_maneusubjectiverefraction_maneuusers_maneuv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManeuAfterSales',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, editable=False, max_length=36, primary_key=True,
                                        serialize=False)),
                ('time', models.DateTimeField()),
                ('order_id', models.CharField(max_length=36)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'maneu_afterSales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManeuDatalogs',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, editable=False, max_length=36, primary_key=True,
                                        serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('time', models.DateField()),
                ('order_log', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'maneu_datalogs',
                'managed': False,
            },
        ),
    ]
